/* This file just contains all messages which are currently stored in the database.
I really need to rearrange my DB structure 'cause it's awkward as hell to work with this. */

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `shortname` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `project` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `needfill` tinyint(1) NOT NULL,
  `fillname` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `messages` (`id`, `shortname`, `project`, `name`, `message`, `needfill`, `fillname`) VALUES
(0, 'c297', 'mc', 'Duplicate of MC-297', '*Thank you for your report!*\\nHowever, this issue is a {color:#FF5722}*Duplicate*{color} of *MC-297*.\\n\\nThis is known to be a problem with your computer.\\n-- Update your [graphics card drivers|https://help.mojang.com/customer/portal/articles/928493-error-bad-video-card-driver]. (Do not rely on automatic updates)\\n-- If you are using Java arguments to increase the amount of memory, please reduce it to the default 512MB.\\n-- If that did not help, please use the *community support* link below.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(1, 'cl5638', 'mcl', 'Duplicate of MCL-5638', '*Thank you for your report!*\\nHowever, this issue is a {color:orangered}*Duplicate*{color} of *MCL-5638*.\\n\\nThis is known to be an issue involving detection of the Java runtime.\\nPlease take a look at the Moderator’s Note on that ticket to see solutions to your issue.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(2, 'cacc', 'mc', 'Account issue', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nThis is an account issue. We do not have the tools to help you on this tracker.\\nPlease use the *customer support* link below.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(3, 'cauth', 'mc', 'Auth server down', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nThe authentication services are offline. Check https://help.mojang.com.\\nThis will be fixed shortly, please hang tight.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(4, 'ccons', 'mc,mcpe,mcapi', 'Wrong project', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nThis is related to a different version of Minecraft. Use one of the links below to go to the correct project.\\n-- [Minecraft: Java Edition|https://bugs.mojang.com/browse/MC] --- PC, Mac and Linux\\n-- [Minecraft: Console Edition|https://bugs.mojang.com/browse/MCCE] --- Xbox 360, Playstation, Wii U and Nintendo Switch\\n-- [Minecraft: Bedrock Edition|https://bugs.mojang.com/browse/MCPE] --- Android, iOS, Windows 10 and Xbox One\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(5, 'cdup', 'mc,mcpe,mcl', 'Duplicate', '*Thank you for your report!*\\nHowever, this issue is a {color:#FF5722}*Duplicate*{color} of *%s%*.\\n\\nIf you have additional information, please add it to that report.\\nPlease [search|https://confluence.atlassian.com/display/JIRA/Basic Searching] before reporting, as it\'s likely that one exists already.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 1, 'Enter parent issue ID'),
(6, 'cdup_p', 'mc,mcpe,mcl', 'Duplicate (private)', '*Thank you for your report!*\\nHowever, this issue is a {color:#FF5722}*Duplicate*{color} of *%s%* (private).\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 1, 'Enter parent issue ID'),
(7, 'cfeat', 'mc,mcpe,mcl', 'Feature request', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nYou have posted a feature request or a suggestion. This site is for *bug reports* only.\\nFor suggestions, please visit [Minecraft Suggestions on Reddit|http://www.reddit.com/r/minecraftsuggestions].\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(8, 'cforce', 'mc', 'Force debug crash report', '*Thank you for your report!*\\nHowever, this issue has been temporarily closed as {color:#FF5722}*Awaiting Response*{color}.\\n\\nWe do not have enough information to find the cause of this issue.\\nPlease force a crash by pressing *F3 + C* for *10 seconds* while in-game and attach the crash report ({{[minecraft/crash-reports/crash-<DATE>-client.txt|http://hopper.minecraft.net/help/guides/finding-minecraft-data-folder]}}) here.\\n\\nOnce attached, the report will be reopened automatically.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(9, 'cint', 'mc,mcpe,mcl', 'Works As Intended', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Working as Intended*{color}.\\n\\nThe report you have submitted is working as intended, mechanics of the game may change between updates.\\nThings such as graphics, sounds, world creation, biomes, redstone, villagers, and animals may not work the same in current versions.\\n\\n[Full Version History|https://minecraft.gamepedia.com/Version_history] -- [Snapshot Version History|https://minecraft.gamepedia.com/Version_history/Development_versions] -- [Feature Requests and Suggestions|https://www.reddit.com/r/minecraftsuggestions]\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(10, 'cfut', 'mc,mcpe,mcl', 'Future Version', '{panel:borderColor=orange}(!) Please do not mark _unreleased versions_ as affected. You don\'t have access to them yet.{panel}\\n', 0, ''),
(11, 'cinc', 'mc,mcl', 'Incomplete', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Incomplete*{color}.\\n\\nYour report does not contain enough information. As such, we\'re unable to understand or reproduce the problem.\\nPlease review the guidelines linked below before making further reports.\\n\\nIn case of a game crash, be sure to attach the crashlog from {{[minecraft/crash-reports/crash-<DATE>-client.txt|http://hopper.minecraft.net/help/guides/finding-minecraft-data-folder]}}.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(12, 'clang', 'mc,mcpe,mcl,mcapi', 'Report not in English', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nBug reports are only accepted in English, sorry.\\nFeel free to create a new report if you can speak English.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(13, 'cmod', 'mc,mcl', 'Modified game', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nYour game, launcher or server is modified.\\nIf you can reproduce the issue in a vanilla environment, please recreate the issue.\\n\\n* Any non-standard client/server/launcher build needs to be taken up with the appropriate team, not Mojang.\\n* Any plugin issues need to be addressed to the creator of the plugin or resource pack.\\n* If you have problems on large servers, such as The Hive and Hypixel, please contact them first as they run modified server software.\\n\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(14, 'cout', 'mc', 'Outdated client', '*Thank you for your report!*\nHowever, this issue is {color:red}*Invalid*{color}.\n\nYour Minecraft version is *outdated*. We currently take issues for version *%s%* and the *latest snapshot*.\nPlease update to the latest version as it includes the newest fixes. If you still have this problem after updating, then please create a new issue.\nIn case of a game crash, please also attach the [crashlog|http://hopper.minecraft.net/help/guides/finding-minecraft-data-folder].\n\n*Quick Links*:\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 1, 'Enter the latest MC version'),
(15, 'cpir', 'mc,mcl', 'Pirated Minecraft', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nYou are currently using a *non-authorized* version of Minecraft. If you wish to purchase the full game, please visit the [Minecraft Store|https://minecraft.net/store].\\nWe will not provide support for pirated versions of the game, these versions are modified and may contain malware.\\n\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(16, 'cpriv', 'mc,mcpe,mcl', 'Private issue', '{panel:borderColor=orange}(!) Please do not mark issues as _private_, unless your bug report is an exploit or contains information about your username or server.{panel}\\n', 0, ''),
(17, 'cquick', 'mc,mcpe,mcl,mcapi', 'Quick links', '*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(18, 'ctech', 'mc,mcl', 'Technical support issue', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nThis is a technical support issue; this site is for bug reports only. We do not have the resources to provide you with technical support.\\nPlease contact the *community support*, linked below.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(19, 'ctrans', 'mc,mcl', 'Translation issue', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nTranslations are done by the community and take place on the [Crowdin Minecraft Translation Project|http://crowdin.net/project/minecraft].\\nPlease use Crowdin for suggesting and adding translations.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(20, 'cmi', 'mc,mcpe,mcl', 'Multiple issues in one report', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nPlease put only one bug report in each ticket. It is very difficult to keep track of bugs when they are not in their own tickets, and it is easier for you to make multiple tickets than for the mods to separate them.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(21, 'ccrash', 'mc,mcl', 'Attach crash report', '_We do not have enough information to find the cause of this issue._\\n\\nPlease *attach the crash report* found in {{[minecraft/crash-reports/crash-<DATE>-client.txt|http://hopper.minecraft.net/help/guides/finding-minecraft-data-folder]}} here.\\nIf you cannot find a crash report, please attach the *full launcher log* found in {{[minecraft/launcher_log.txt|http://hopper.minecraft.net/help/guides/minecraft-logs/]}}.\\n\\n~This issue has been temporarily closed as {color:#d04437}*Awaiting Response*{color}. Once the requested information has been delivered, the report will be reopened automatically.~\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(22, 'cmin', 'mc,mcl', 'Minimum requirements not met', '*Thank you for your report!* \\nHowever, this issue is {color:red}*Invalid*{color}.\\n\\nYour computer does not meet the [minimum system requirements|https://help.mojang.com/customer/en/portal/articles/325948-minecraft-system-requirements] to run Minecraft.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(23, 'cmod', 'mcpe', 'Modified game', '*Thank you for your report!*\\nHowever, this issue is {color:#FF5722}*Invalid*{color}.\\n\\nThe server you are playing on is modified.\\nIf you can reproduce the issue in a vanilla environment, please recreate the issue.\\n\\n* Any non-standard client/server build needs to be taken up with the appropriate team, not Mojang.\\n* Any plugin issues need to be addressed to the creator of the plugin, add-on or resource pack.\\n* If you have problems on large servers, such as Mineplex and Lifeboat, please contact them first as they run modified server software.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(24, 'clog', 'mcpe', 'Crash logged automatically', '*Thank you for your report!*\\n\\nCrashes such as these are now logged automatically, this will therefore be investigated further by the development team internally.\\n\\n*Quick Links*:\\n📓 [Issue Guidelines|https://help.mojang.com/customer/portal/articles/801354-writing-helpful-bug-reports-for-minecraft] -- 💬 [Community Support|http://hopper.minecraft.net/help/technical-support-resources/] -- 📧 [Customer Support|https://help.mojang.com/customer/portal/emails/new] -- 📖 [Game Wiki|https://minecraft.gamepedia.com/Minecraft_Wiki]', 0, ''),
(25, 'chash', 'mcpe', 'Hashtag issue', 'For any new or ongoing hashtag issues, please create a new ticket for any gamertags still affected and use the label {{[chat-filter|https://bugs.mojang.com/issues/?jql=labels+%3D+chat-filter]}}.', 0, ''),
(26, 'cparity', 'mc,mcpe', 'Parity issue', 'Minecraft has several different editions, and some features vary from edition to edition. Often this happens when one edition evolves faster than another, and tweaks or balances are made that don\'t propagate immediately to other editions.', 0, '');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
